site_name: ASGA

nav:
  - Home: index.md
  - Documentation: doc.md
  - About: 
      - License: license.md
      - 'Release Note': Change_Log.md
      - Citation: Cit.md

repo_url: https://github.com/RRobert92/ASGA
site_url: https://github.com/RRobert92/ASGA